version: "3.8"

services:
    api:
        build: ./app
        ports: 
            - 80:80
        environment:
            - DB_URL=mongodb://db/
        volumes:
            - ./app:/app
    db:
        image: mongo
        volumes:
            - taskdb:/data/db
        command: --quiet
volumes:
  taskdb:


